model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 1024


data_params:
  data_path: "folds/ind_fold.yaml"
  train_batch_size: 16
  val_batch_size:  16
  patch_size: 512
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 200

logging_params:
  save_dir: "VAEs/"
  name: "nico_dim"
  
